# Generated by Django 4.1.4 on 2022-12-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindBnBCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adress', models.TextField(default='')),
                ('starsRate', models.FloatField(default=0, max_length=255)),
                ('priceForNight', models.IntegerField(default=0)),
                ('isSuperhost', models.BooleanField(default=False)),
                ('freewifi', models.BooleanField(default=False)),
                ('nocancelationfee', models.BooleanField(default=False)),
                ('securitysystems', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=255)),
                ('preview_image', models.ImageField(default='media/pictures/default_house.png', upload_to='pictures')),
                ('owner', models.CharField(default='', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/pictures/default_house.png', upload_to='pictures')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.windbnbcardmodel')),
            ],
        ),
    ]
