# Generated by Django 4.1.4 on 2022-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_windbnbcard_windbnbcardmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windbnbcardmodel',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='freewifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='isSuperhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='nocancelationfee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='owner',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='securitysystems',
            field=models.BooleanField(default=False),
        ),
    ]
