# Generated by Django 4.1.4 on 2023-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_windbnbcardmodel_location_real_alter_owner_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windbnbcardmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
