# Generated by Django 4.1.4 on 2022-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_desc_windbnbcardmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='adress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='priceForNight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='starsRate',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
