# Generated by Django 4.1.4 on 2023-01-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_windbnbcardmodel_location_location_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windbnbcardmodel',
            old_name='location_real',
            new_name='location',
        ),
    ]
