# Generated by Django 4.1.4 on 2022-12-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_windbnbcardmodel_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windbnbcardmodel',
            name='preview_image',
            field=models.ImageField(default='pictures/default_house.png', upload_to='pictures'),
        ),
    ]
