# Generated by Django 4.1.4 on 2022-12-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_windbnbcardmodel_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windbnbcardmodel',
            name='preview_image',
            field=models.ImageField(default='media/pictures/default_house.png', upload_to='pictures'),
        ),
    ]
