# Generated by Django 4.1.4 on 2022-12-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='media/pictures/default_house.png', upload_to='pictures'),
        ),
    ]
